FROM smerrill/vagrant-centos
MAINTAINER Steven Merrill <steven.merrill@gmail.com>

# Install Puppet 3.4.3.
RUN yum -y localinstall http://yum.puppetlabs.com/puppetlabs-release-el-6.noarch.rpm && yum -y install puppet-3.4.3 facter hiera
